---
kind: pipeline
name: container

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  image: plugins/docker
  settings:
    build_args:
    - BUILD_VERSION=${DRONE_TAG%-*}
    build_args_from_env:
    - COLLABORA_TOKEN
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: registry.owncloud.com/${DRONE_REPO_NAME}/server
    username:
      from_secret: docker_username
  environment:
    COLLABORA_TOKEN:
      from_secret: collabora_token
  when:
    ref:
    - refs/pull/**

- name: tags
  image: alpine
  commands:
  - export BASE=${DRONE_TAG:-latest}
  - export TAG=$${BASE##v}
  - if [ "$$TAG" == "latest" ]; then echo -n "latest" > .tags; else echo -n "latest,$${TAG},$${TAG%-*},$${TAG%.*},$${TAG%%.*}" > .tags; fi

- name: publish
  image: plugins/docker
  settings:
    build_args:
    - BUILD_VERSION=${DRONE_TAG%-*}
    build_args_from_env:
    - COLLABORA_TOKEN
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: registry.owncloud.com/${DRONE_REPO_NAME}/server
    username:
      from_secret: docker_username
  environment:
    COLLABORA_TOKEN:
      from_secret: collabora_token
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private
  when:
    status:
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- container

...
